org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.255
neo_version_range=[21.1.219,)
loader_version_range=[4,)
mod_id=ef_tlm
mod_name=EpicFight_TouhouLittleMaid
mod_disname=[史诗战斗：车万女仆]
mod_license=All Rights Reserved
mod_version=1.3.5
mod_group_id=net
mod_authors=XcS
mod_description=女仆也能充满Power！Toggle Fight Mode！
epicfight_version=21.17.3.1-mc1.21.1-neoforge
