modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="ef_tlm"
version="1.3.5"
displayName="史诗战斗：车万女仆"
authors="XcS"
logoFile="LOGO.png"
description='''
女仆也能充满Power！Toggle Fight Mode！
'''

[[mixins]]
config="ef_tlm.mixins.json"

[[mixins]]
config="ef_tlm.efn.mixins.json"

[[dependencies.ef_tlm]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies.ef_tlm]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.ef_tlm]]
modId="epicfight"
type="required"
versionRange="[21.15.6,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ef_tlm]]
modId="epic_fight_avalon"
type="required"
versionRange="[21,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ef_tlm]]
modId="touhou_little_maid"
type="required"
versionRange="[1.5.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ef_tlm]]
modId="efn"
type="optional"
versionRange="[3.4,)"
ordering="AFTER"
side="BOTH"
